In [15]:
import pandas as pd

pd.set_option('display.max_columns', None) #To display all columns
pd.set_option('display.expand_frame_repr', False) 

df = pd.read_csv('train.csv', nrows=1000000) #Read only first 10000 rows
df.head(100)

              id  click      hour    C1  banner_pos   site_id site_domain site_category    app_id app_domain app_category device_id device_ip device_model  device_type  device_conn_type    C14  C15  C16   C17  C18  C19     C20  C21
0   1.000009e+18      0  14102100  1005           0  1fbe01fe    f3845767      28905ebd  ecad2386   7801e8d9     07d7df22  a99f214a  ddd2926e     44956a24            1                 2  15706  320   50  1722    0   35      -1   79
1   1.000017e+19      0  14102100  1005           0  1fbe01fe    f3845767      28905ebd  ecad2386   7801e8d9     07d7df22  a99f214a  96809ac8     711ee120            1                 0  15704  320   50  1722    0   35  100084   79
2   1.000037e+19      0  14102100  1005           0  1fbe01fe    f3845767      28905ebd  ecad2386   7801e8d9     07d7df22  a99f214a  b3cf8def     8a4875bd            1                 0  15704  320   50  1722    0   35  100084   79
3   1.000064e+19      0  14102100  1005           0  1fbe01fe    f3845767      28905ebd  ecad2386   7801e8d9     07d7df22  a99f214a  e8275b8f     6332421a            1                 0  15706  320   50  1722    0   35  100084   79
4   1.000068e+19      0  14102100  1005           1  fe8cc448    9166c161      0569f928  ecad2386   7801e8d9     07d7df22  a99f214a  9644d0bf     779d90c2            1                 0  18993  320   50  2161    0   35      -1  157
..           ...    ...       ...   ...         ...       ...         ...           ...       ...        ...          ...       ...       ...          ...          ...               ...    ...  ...  ...   ...  ...  ...     ...  ...
95  1.001538e+19      0  14102100  1005           0  1fbe01fe    f3845767      28905ebd  ecad2386   7801e8d9     07d7df22  a99f214a  03108db9     a0f5f879            1                 0  15701  320   50  1722    0   35  100084   79
96  1.001541e+19      1  14102100  1005           0  1fbe01fe    f3845767      28905ebd  ecad2386   7801e8d9     07d7df22  a99f214a  0b697be1     1f0bc64f            1                 0  15701  320   50  1722    0   35  100084   79
97  1.001563e+19      1  14102100  1005           0  1fbe01fe    f3845767      28905ebd  ecad2386   7801e8d9     07d7df22  a99f214a  58db4f0c     6332421a            1                 0  15708  320   50  1722    0   35      -1   79
98  1.001570e+17      0  14102100  1005           0  1fbe01fe    f3845767      28905ebd  ecad2386   7801e8d9     07d7df22  a99f214a  02b9b0fc     1aa0e912            1                 0  15706  320   50  1722    0   35      -1   79
99  1.001575e+19      0  14102100  1005           0  1fbe01fe    f3845767      28905ebd  ecad2386   7801e8d9     07d7df22  a99f214a  6b9769f2     4c8aeb60            1                 0  15701  320   50  1722    0   35      -1   79

[100 rows x 24 columns]

In [16]:
# Dataset was shuffled with command bash
dataset = r'train_shuffled_with_columns.csv' 
df = pd.read_csv(dataset,nrows=1000000)
df.head(100)

                      id  click      hour    C1  banner_pos   site_id site_domain site_category    app_id app_domain app_category device_id device_ip device_model  device_type  device_conn_type    C14  C15  C16   C17  C18  C19     C20  C21
0   10057999713518154267      1  14103004  1005           0  85f751fd    c4e18dd6      50e219e0  9c13b419   2347f47a     f95efa07  a99f214a  246f04b1     1c309a38            1                 0  23160  320   50  2667    0   35      -1  221
1   14122329642764882721      0  14102310  1005           0  85f751fd    c4e18dd6      50e219e0  7358e05e   b9528b13     cef3e649  0d1b778d  1ba55873     a5bce124            1                 0  16615  320   50  1863    3   39      -1   23
2   10721012164553134309      0  14103020  1005           1  856e6d3f    58a89a43      f028772b  ecad2386   7801e8d9     07d7df22  a99f214a  bd97fd1f     1f0bc64f            1                 0  23996  320   50  2748    0   35  100130   79
3    9490058727388527927      0  14102108  1005           1  43d6df75    27e3c518      28905ebd  ecad2386   7801e8d9     07d7df22  a99f214a  16216c64     24f6b932            1                 0  15708  320   50  1722    0   35  100083   79
4   10778247262504734817      0  14102805  1005           1  ba9aee1b    9eaf88fa      f028772b  ecad2386   7801e8d9     07d7df22  a99f214a  98e1db9e     6e1e2240            1                 0  22681  320   50  2528    0   39  100077  221
..                   ...    ...       ...   ...         ...       ...         ...           ...       ...        ...          ...       ...       ...          ...          ...               ...    ...  ...  ...   ...  ...  ...     ...  ...
95   9778246556510014526      0  14102515  1005           0  85f751fd    c4e18dd6      50e219e0  7ea7d18e   2347f47a     0f2161f8  a99f214a  e956f140     d787e91b            1                 0   6393  320   50   547    3   47      -1   23
96   7877619211570899345      0  14102707  1010           1  85f751fd    c4e18dd6      50e219e0  8c0dcd5a   7801e8d9     0f2161f8  7da9c5c3  0570d80f     e710234d            4                 0  21155  320   50  2420    2   35      -1   69
97   6121328688298564945      0  14102509  1002           0  7dd7ac7b    1e0acfb4      50e219e0  ecad2386   7801e8d9     07d7df22  0ff9c29e  cd79c09d     e96b49d6            0                 0  21409  320   50  2467    2  167  100077   23
98   9557963565102350565      0  14102202  1010           1  85f751fd    c4e18dd6      50e219e0  30270b79   7801e8d9     09481d60  b61bc26a  74c2f751     f07e20f8            4                 2  17877  320   50  2036    3   47      -1  156
99   4779420988272161839      0  14102510  1005           0  b99a2c43    cc962a1f      f028772b  ecad2386   7801e8d9     07d7df22  a99f214a  009a7861     d104784a            1                 0  22288  320   50  2572    3  297  100156   42

[100 rows x 24 columns]

# Exploring DataSet

In [17]:
#To display all columns
df.columns

Index(['id', 'click', 'hour', 'C1', 'banner_pos', 'site_id', 'site_domain',
       'site_category', 'app_id', 'app_domain', 'app_category', 'device_id',
       'device_ip', 'device_model', 'device_type', 'device_conn_type', 'C14',
       'C15', 'C16', 'C17', 'C18', 'C19', 'C20', 'C21'],
      dtype='object')

In [18]:
# Get the number of unique values in each column
unique_counts = df.nunique()
print(unique_counts)

id                  1000000
click                     2
hour                    240
C1                        7
banner_pos                7
site_id                2674
site_domain            2883
site_category            21
app_id                 3116
app_domain              214
app_category             25
device_id            150242
device_ip            554737
device_model           5187
device_type               5
device_conn_type          4
C14                    2255
C15                       8
C16                       9
C17                     420
C18                       4
C19                      66
C20                     161
C21                      60
dtype: int64

In [19]:
# Get the number of missing values in each column
missing_counts = df.isnull().sum()
print(missing_counts)

id                  0
click               0
hour                0
C1                  0
banner_pos          0
site_id             0
site_domain         0
site_category       0
app_id              0
app_domain          0
app_category        0
device_id           0
device_ip           0
device_model        0
device_type         0
device_conn_type    0
C14                 0
C15                 0
C16                 0
C17                 0
C18                 0
C19                 0
C20                 0
C21                 0
dtype: int64

In [20]:
# Get the data type of each column
data_types = df.dtypes
print(data_types)

id                  uint64
click                int64
hour                 int64
C1                   int64
banner_pos           int64
site_id             object
site_domain         object
site_category       object
app_id              object
app_domain          object
app_category        object
device_id           object
device_ip           object
device_model        object
device_type          int64
device_conn_type     int64
C14                  int64
C15                  int64
C16                  int64
C17                  int64
C18                  int64
C19                  int64
C20                  int64
C21                  int64
dtype: object

In [21]:
# Examine imbalance in the target variable 'click'
click_values = df['click'].value_counts()
print(click_values)

print("Imbalance ratio: {}".format(float(len(df[df['click']==0]))/len(df[df['click']==1])))

click
0    830446
1    169554
Name: count, dtype: int64
Imbalance ratio: 4.8978260613138

In [22]:
# Calculating the click through rate in our sample
CTR = df['click'].mean()
print(CTR)

0.169554

# Preprocessing

In [23]:
# Deleting id column
df = df.drop('id', axis=1)
df.head()

   click      hour    C1  banner_pos   site_id site_domain site_category    app_id app_domain app_category device_id device_ip device_model  device_type  device_conn_type    C14  C15  C16   C17  C18  C19     C20  C21
0      1  14103004  1005           0  85f751fd    c4e18dd6      50e219e0  9c13b419   2347f47a     f95efa07  a99f214a  246f04b1     1c309a38            1                 0  23160  320   50  2667    0   35      -1  221
1      0  14102310  1005           0  85f751fd    c4e18dd6      50e219e0  7358e05e   b9528b13     cef3e649  0d1b778d  1ba55873     a5bce124            1                 0  16615  320   50  1863    3   39      -1   23
2      0  14103020  1005           1  856e6d3f    58a89a43      f028772b  ecad2386   7801e8d9     07d7df22  a99f214a  bd97fd1f     1f0bc64f            1                 0  23996  320   50  2748    0   35  100130   79
3      0  14102108  1005           1  43d6df75    27e3c518      28905ebd  ecad2386   7801e8d9     07d7df22  a99f214a  16216c64     24f6b932            1                 0  15708  320   50  1722    0   35  100083   79
4      0  14102805  1005           1  ba9aee1b    9eaf88fa      f028772b  ecad2386   7801e8d9     07d7df22  a99f214a  98e1db9e     6e1e2240            1                 0  22681  320   50  2528    0   39  100077  221

In [24]:
from datetime import datetime

df['hour'] = df['hour'].map(lambda x: datetime.strptime(str(x), "%y%m%d%H"))
df['day_of_week'] = df['hour'].map(lambda x: x.weekday())
df['hour'] = df['hour'].map(lambda x: x.hour)

df.head()

   click  hour    C1  banner_pos   site_id site_domain site_category    app_id app_domain app_category device_id device_ip device_model  device_type  device_conn_type    C14  C15  C16   C17  C18  C19     C20  C21  day_of_week
0      1     4  1005           0  85f751fd    c4e18dd6      50e219e0  9c13b419   2347f47a     f95efa07  a99f214a  246f04b1     1c309a38            1                 0  23160  320   50  2667    0   35      -1  221            3
1      0    10  1005           0  85f751fd    c4e18dd6      50e219e0  7358e05e   b9528b13     cef3e649  0d1b778d  1ba55873     a5bce124            1                 0  16615  320   50  1863    3   39      -1   23            3
2      0    20  1005           1  856e6d3f    58a89a43      f028772b  ecad2386   7801e8d9     07d7df22  a99f214a  bd97fd1f     1f0bc64f            1                 0  23996  320   50  2748    0   35  100130   79            3
3      0     8  1005           1  43d6df75    27e3c518      28905ebd  ecad2386   7801e8d9     07d7df22  a99f214a  16216c64     24f6b932            1                 0  15708  320   50  1722    0   35  100083   79            1
4      0     5  1005           1  ba9aee1b    9eaf88fa      f028772b  ecad2386   7801e8d9     07d7df22  a99f214a  98e1db9e     6e1e2240            1                 0  22681  320   50  2528    0   39  100077  221            1

In [25]:
df.nunique()

click                    2
hour                    24
C1                       7
banner_pos               7
site_id               2674
site_domain           2883
site_category           21
app_id                3116
app_domain             214
app_category            25
device_id           150242
device_ip           554737
device_model          5187
device_type              5
device_conn_type         4
C14                   2255
C15                      8
C16                      9
C17                    420
C18                      4
C19                     66
C20                    161
C21                     60
day_of_week              7
dtype: int64

In [26]:
#testing 2